# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604016987a76630cca84fd1408f09a9396d6a4676951f3194a363bda98144d0b375ff5e654d777745e6e95d7149f9eee602c5f9ae7e8cb231a2b78aa9734bf72

test:
  secret_key_base: d46362faa850b06acbcc40440f4a3e83e0f2fb8637aa0d27b7c865897653cd57297797572ab0b80d889443804506f43a5f7d2335ad918e6dc1caa2b850bca77b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
